/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 CAVALLO.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CAVALLO.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[0, 0, -0.239]} scale={0.224}>
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/CAVALLO.glb')
